# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('base_power', models.IntegerField()),
                ('base_accuracy', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('positive', models.CharField(max_length=10)),
                ('negative', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('egg_group', models.CharField(max_length=30)),
                ('national_dex', models.IntegerField()),
                ('types', django.contrib.postgres.fields.jsonb.JSONField()),
                ('resistences', django.contrib.postgres.fields.jsonb.JSONField()),
                ('weaknesses', django.contrib.postgres.fields.jsonb.JSONField()),
                ('immunities', django.contrib.postgres.fields.jsonb.JSONField()),
                ('stage', models.CharField(max_length=10)),
                ('hitpoints', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resistences', django.contrib.postgres.fields.jsonb.JSONField()),
                ('weaknesses', django.contrib.postgres.fields.jsonb.JSONField()),
                ('immunities', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
