# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 22:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='move',
            old_name='type',
            new_name='atk_type',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='egg_group',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_groups',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evs',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
